module.exports = {
  "created_at":"Mon Dec 15 14:10:11 +0000 2014",
  "id":544494635046154240,
  "id_str":"1",
  "text":"@gramobot fooo 1 #test https://t.co/v1qEV7JOfU",
  "source":"<a href=\"https://about.twitter.com/products/tweetdeck\" rel=\"nofollow\">TweetDeck</a>",
  "truncated":false,
  "in_reply_to_status_id":null,
  "in_reply_to_status_id_str":null,
  "in_reply_to_user_id":2382616447,
  "in_reply_to_user_id_str":"2382616447",
  "in_reply_to_screen_name":"bla_user",
  "user":{
    "id":2382616447,
    "id_str":"2382616447",
    "name":"gramobot",
    "screen_name":"mietzecutze",
    "location":"",
    "url":"http://www.gramobot.com",
    "description":null,
    "protected":false,
    "verified":false,
    "followers_count":2,
    "friends_count":3,
    "listed_count":0,
    "favourites_count":0,
    "statuses_count":16,
    "created_at":"Mon Mar 10 19:56:10 +0000 2014",
    "utc_offset":3600,
    "time_zone":"Amsterdam",
    "geo_enabled":false,
    "lang":"en",
    "contributors_enabled":false,
    "is_translator":false,
    "profile_background_color":"333333",
    "profile_background_image_url":"http://abs.twimg.com/images/themes/theme16/bg.gif",
    "profile_background_image_url_https":"https://abs.twimg.com/images/themes/theme16/bg.gif",
    "profile_background_tile":true,
    "profile_link_color":"0084B4",
    "profile_sidebar_border_color":"FFFFFF",
    "profile_sidebar_fill_color":"DDEEF6",
    "profile_text_color":"333333",
    "profile_use_background_image":false,
    "profile_image_url":"http://pbs.twimg.com/profile_images/443140775623139329/SbA-FaoC_normal.jpeg",
    "profile_image_url_https":"/images/fakeavatars/cat.webp",
    "default_profile":false,
    "default_profile_image":false,
    "following":null,
    "follow_request_sent":null,
    "notifications":null
  },
  "geo":null,
  "coordinates":null,
  "place":null,
  "contributors":null,
  "retweet_count":0,
  "favorite_count":0,
  "entities":{
    "hashtags":[
      {
        "text":"test",
        "indices":[
          15,
          23
        ]
      }
    ],
    "trends":[],
    "urls":[{
      "url":"https://t.co/v1qEV7JOfU",
      "expanded_url":"https://www.youtube.com/watch?v=XfR9iY5y94s",
      "display_url":"youtube.com/watch?v=UPoXG1.",
      "indices":[ 24, 47 ]
    }
    ],
    "user_mentions":[
      {
        "screen_name":"gramobot",
        "name":"gramobot",
        "id":2382616447,
        "id_str":"2382616447",
        "indices":[0,9]
      }
    ],
    "symbols":[]
  },
  "favorited":false,
  "retweeted":false,
  "possibly_sensitive":false,
  "filter_level":"medium",
  "lang":"und",
  "timestamp_ms":"1418652611873"
}